version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - recipe-app-network
  pgadmin:
    image: dpage/pgadmin4:7.3
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_PASSWORD}'
    ports:
      - '5050:80'
    profiles:
      - tools
    networks:
      - recipe-app-network
  cache:
    image: redis:7.0.12-apline
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass '${REDIS_PASSWORD}'
    volumes:
      - cache:/data
    networks:
      - recipe-app-network

volumes:
  db:
    driver: local
  cache:
    driver: local

networks:
  recipe-app-network:
    driver: bridge
