version: 2.1
orbs:
  github-super-linter: circleci/github-super-linter@1.0.1

commands:
  install_dependencies:
    steps:
      - run:
          name: Install node dependencies
          command: npm install
  setup_prisma:
    steps:
      - run:
          name: Generate prisma model
          command: npx prisma generate
      - run:
          name: Generate and apply migration
          command: npx prisma migrate dev
  setup_docker_compose:
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Run images of services declared in docker-compose.yml
          command: docker-compose up -d

jobs:
  build_and_test:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.16.0
      - image: cimg/postgres:14.1
    steps:
      - checkout
      - install_dependencies
      - setup_prisma
      - setup_docker_compose
      - run:
          name: Run unit tests
          command: npm run test
      - run:
          name: Run e2e tests
          command: npm run test:e2e

  deploy:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - install_dependencies
      - run: echo "!TODO"

workflows:
  build_and_test:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: main
