-- DropForeignKey
ALTER TABLE "PAT" DROP CONSTRAINT "PAT_userId_fkey";

-- DropIndex
DROP INDEX "PAT_userId_key";

-- AddForeignKey
ALTER TABLE "PAT" ADD CONSTRAINT "PAT_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
